version: '3'
services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  frontend:
    image: pl-frontend
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
     - ./frontend:/usr/src/pl-frontend # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
     - REACT_APP_BACKEND_URL=http://localhost:8080/api
    ports:
     - 3000:3000
    container_name: pl-frontend # This will name the container todo-frontend

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=example
     - MONGO_INITDB_DATABASE=the_database
    volumes:
     - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
     - ./backend/mongo_data:/data/db
    container_name: "mongo-container"
    
  backend:
    image: pl-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
     - ./backend:/usr/src/pl-backend
    ports:
     - 3001:3001
    container_name: pl-backend
    environment: 
      - PORT=3001
      - MONGO_URL=mongodb://the_username:the_password@mongo-container:27017/the_database